# Generated by Django 5.2.7 on 2026-01-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_merge_transaction_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_payment_bc131d_idx',
            old_name='orders_orde_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_transac_6ad70c_idx',
            old_name='orders_orde_transact_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_gateway_ceea55_idx',
            old_name='orders_orde_gateway_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره رسید روزانه'),
        ),
    ]
