# Generated by Django 4.2.16 on 2025-12-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='شناسه تراکنش')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه سفارش')),
                ('order_details', models.JSONField(blank=True, null=True, verbose_name='جزئیات سفارش')),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='روش پرداخت')),
                ('gateway_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام Gateway')),
                ('gateway_request_data', models.JSONField(blank=True, null=True, verbose_name='داده درخواست Gateway')),
                ('gateway_response_data', models.JSONField(blank=True, null=True, verbose_name='داده پاسخ Gateway')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='payment_tra_transac_143f1c_idx'), models.Index(fields=['order_id'], name='payment_tra_order_i_c6a3d5_idx'), models.Index(fields=['status'], name='payment_tra_status_373de7_idx'), models.Index(fields=['gateway_name'], name='payment_tra_gateway_ad409f_idx')],
            },
        ),
    ]
